name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: chmod +x gradlew && ./gradlew -PspaceUser=${SPACE_USERNAME} -PspacePassword=${SPACE_PASSWORD} clean build
      env:
        SPACE_USERNAME: ${{ secrets.SPACE_USERNAME }}
        SPACE_PASSWORD: ${{ secrets.SPACE_PASSWORD }}
    - name: Publish artifacts
      run: ./gradlew -PspaceUser=${SPACE_USERNAME} -PspacePassword=${SPACE_PASSWORD} lib:publish
      env:
        SPACE_USERNAME: ${{ secrets.SPACE_USERNAME }}
        SPACE_PASSWORD: ${{ secrets.SPACE_PASSWORD }}
